# Generated by Django 5.2.5 on 2025-09-16 15:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название звена сети",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail_network", "Розничная сеть"),
                            (
                                "individual_entrepreneur",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        help_text="Тип звена в сети",
                        max_length=30,
                        verbose_name="Тип звена",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Электронная почта",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Страна расположения",
                        max_length=100,
                        verbose_name="Страна",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Город расположения",
                        max_length=100,
                        verbose_name="Город",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Название улицы", max_length=255, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        help_text="Номер дома", max_length=20, verbose_name="Номер дома"
                    ),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Задолженность в рублях с точностью до копеек",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Поставщик оборудования",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="electronics_network.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active_employee",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, имеет ли сотрудник доступ к API",
                        verbose_name="Активный сотрудник",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "network_node",
                    models.ForeignKey(
                        blank=True,
                        help_text="Звено сети, к которому привязан сотрудник",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="electronics_network.networknode",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название продукта",
                        max_length=255,
                        verbose_name="Название продукта",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Модель продукта",
                        max_length=255,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        help_text="Дата выхода продукта на рынок",
                        verbose_name="Дата выхода на рынок",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "network_node",
                    models.ForeignKey(
                        help_text="Звено сети, которое продает этот продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="electronics_network.networknode",
                        verbose_name="Звено сети",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["-created_at"],
                "unique_together": {("name", "model", "network_node")},
            },
        ),
    ]
